apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: scanner
    tier: backend
  name: scanner
  namespace: yasp
spec:
  replicas: 1
  selector:
    app: scanner
    tier: backend
  template:
    metadata:
      labels:
        app: scanner
        tier: backend
    spec:
      volumes:
      - name: api-keys
        secret:
          secretName: api-keys
      containers:
      - name: yasp
        image: yasp/yasp:latest
        args: [ "node", "scanner.js" ]
        imagePullPolicy: Always
        volumeMounts:
        - name: api-keys
          readOnly: true
          mountPath: /etc/yasp-api-keys
      restartPolicy: Always